services:
  backend:
    build:
      context: .
      dockerfile: docker/apache-php.dockerfile
    container_name: ci3-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - erpnet
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: docker/node.dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - erpnet

networks:
  erpnet:
    driver: bridge
