services:
  backend:
    build:
      context: .
      dockerfile: docker/apache-php.dockerfile
    container_name: ci3-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - erpnet
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - CI_ENV=development

  frontend:
    build:
      context: .
      dockerfile: docker/node.dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - erpnet

  db:
    image: mysql:8.0
    container_name: erp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d
    networks:
      - erpnet

networks:
  erpnet:
    driver: bridge

volumes:
  db_data:
